spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:3306/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}


  redis:
    host: ${REDIS_HOST}
    port: 6379
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  security:
    debug: true
